### ISSUE TITLE
add riehle role constraints

### ISSUE THREAD

**Issue by SebLeich** [Eden-06/FRaMED-io#44]

**Comment by SebLeich** [comment]
![Unbenannt](https://user-images.githubusercontent.com/22755574/57380063-73a2bc00-71a8-11e9-8f3a-e260086c6c53.PNG)

**Comment by Oberacda** [comment]
Development of this features takes place in the [add-riehle-role-constraints](/Eden-06/FRaMED-io/tree/add-riehle-role-constraints) branch.

**Comment by Oberacda** [comment]
# Design ToDo's

## CyclicChooser
The increased amount of selection option creates a problem with the CyclicChooser and the ConnectionManagerLinker.
There are two possible solutions:

* Rework the CyclicChooser to allow for more then 4 options. This has the disadvantage of complicating the keyboard shortcuts.
* Allow nested selections with the cyclic chooser. This requires detection of categories for the different element types. This is currently not possible.

## ProhibitionRelation Arrows

Due the way that JsPlumb draws connection and overlays, the line extends behind the arrow end for the prohibition arrow end.
This cannot be avoided with JsPlumb.

The placement of the arrow heads requires a modification of the ConnectionEnd visual element. Here the question is if there should be a separate subtypes for target and source ConnectionEnds to implement.

**Comment by Oberacda** [comment]
> The increased amount of selection option creates a problem with the CyclicChooser and the ConnectionManagerLinker.
> There are two possible solutions:
> 
>    * **Rework the CyclicChooser to allow for more then 4 options. This has the disadvantage of complicating the keyboard shortcuts.**
> 
>    * ~~Allow nested selections with the cyclic chooser. This requires detection of categories for the different element types. This is currently not possible.~~
> 

* Use numerical shortcuts to address the individual items.

---

> 
> ## ProhibitionRelation Arrows
> 
> Due the way that JsPlumb draws connection and overlays, the line extends behind the arrow end for the prohibition arrow end.
> This cannot be avoided with JsPlumb.
> 
> The placement of the arrow heads requires a modification of the ConnectionEnd visual element. Here the question is if there should be a separate subtypes for target and source ConnectionEnds to implement.

* Add an Enum to define the layout of the arrowheads for ConnectionEnds.

---

* Riehle constraint targets are restricted to the compartment / scene of the source role.

---

* Expand Test scope to cover the role constraints as far as possible.
