### ISSUE TITLE
getAncestors function not working properly

### ISSUE THREAD

**Issue by Oberacda** [Eden-06/FRaMED-io#67]
The function `getAncestors` does not properly return all ancestors of a nested element.
```kotlin
private tailrec fun Linker<*, *>.getAncestors(accumulator: List<ShapeLinker<*, *>> = emptyList()): List<ShapeLinker<*, *>> {
        if (this !is ShapeLinker<*, *>) return emptyList()
        val parent = parent
        @Suppress("IfThenToElvis")
        return if (parent == null) {
            listOf(this)
        } else {
            parent.getAncestors(accumulator + this)
        }
    }
```

Replacing the code with the function below causes the `is not a function` javascript error:

```kotlin
private fun Linker<*, *>.getAncestors(): List<ShapeLinker<*, *>> {
        if (this !is ShapeLinker<*, *>) return emptyList()

        val ancestors = mutableListOf<ShapeLinker<*,*>>()
        var parent = this.parent
        while (parent != null) {
            ancestors += parent 
            parent = parent .parent
        }
        return ancestors 
    }
```

**Comment by pixix4** [comment]
This is a bug in the `legacy` kotlin-js compiler. With the newer `IR` compiler this bug does not occur anymore.

To fix the bug temporarily, you can drag the function out of the interface and put it on file level in `LinkerInfoConnection.kt` as a private function (i.e. move the function to the end of the file after the last closing curly bracket). This changes the binding context and prevents the ambiguity of the `this` object.

**Comment by Oberacda** [comment]
The second implementation works as intended with the suggested workaround. The original implementation still does not work as intended and only returns the first ancestor.

**Comment by Oberacda** [comment]
The tail recursion in the original implementation is wrong. The corrected version works as intended in conjunction with the workaround for the compiler issue.
